# Generated by Django 3.0.3 on 2020-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paytm_txn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
