# Generated by Django 3.0.3 on 2020-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200325_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paytm_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
