# Generated by Django 3.0.3 on 2020-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
