# Generated by Django 3.0.3 on 2020-04-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200414_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='txn_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
