# Generated by Django 3.0.3 on 2020-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
