# Generated by Django 3.0.3 on 2020-04-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
