# Generated by Django 3.0.3 on 2020-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200404_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
